"""add citations to messages

Revision ID: 0e8d1c41b5a0
Revises: 57691c74bd18
Create Date: 2026-09-19 05:05:02.268722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e8d1c41b5a0'
down_revision: Union[str, Sequence[str], None] = '57691c74bd18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('citations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'citations')
    # ### end Alembic commands ###
