"""create source pages

Revision ID: 147084daf99e
Revises: a6292e7aa3a2
Create Date: 2026-09-14 14:34:10.739190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147084daf99e'
down_revision: Union[str, Sequence[str], None] = 'a6292e7aa3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'page_number', name='uq_source_page')
    )
    op.create_index(op.f('ix_source_pages_id'), 'source_pages', ['id'], unique=False)
    op.create_index(op.f('ix_source_pages_source_id'), 'source_pages', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_pages_source_id'), table_name='source_pages')
    op.drop_index(op.f('ix_source_pages_id'), table_name='source_pages')
    op.drop_table('source_pages')
    # ### end Alembic commands ###
